[package]
name = "kernel"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common/" }
interrupt-macro = { path = "../interrupt-macro/" }
log = "0.4"
x86 = "0.51"
aligned = "0.4"
bitmask-enum = "1.1"
generic-array = "0.14"
linked_list_allocator = "0.9"
lazy_static = { version = "1.4", default_features = false, features = [ "spin_no_std" ] }
num-traits = { version = "0.2", default_features = false }
compression = { version = "0.1", default_features = false, features = [ "gzip", "bzip2" ] }
raw-cpuid = "10.6"
spin = "0.9"
volatile = "0.4"
goblin = { version = "0.5", default-features = false, features = [ "elf32", "elf64", "endian_fd" ] }

[build-dependencies]
cc = "1.0"
