[unstable]
build-std-features = [ "compiler-builtins-mem" ]
build-std = [ "core", "compiler_builtins", "alloc" ]

[build]
target = "i586-unknown-none.json"
rustflags = [ "--cfg", "target_arch=\"i586\"", "--cfg", "target_platform=\"ibmpc\"" ]
